import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


REPO = Path.cwd()
TOPICS_DIR = REPO / "Topics"


def git_sha(path):
    """Return the Git blob SHA for a file."""
    result = subprocess.run(
        ["git", "hash-object", str(path)],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace(
        "+00:00", "Z"
    )


def load_topic_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_topic_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def main():
    print("=" * 70)
    print("LeetHub-Neo metadata migration")
    print("=" * 70)

    topic_files = list(TOPICS_DIR.glob("*/problems.json"))

    if not topic_files:
        print("ERROR: No Topics/*/problems.json files found.")
        return

    print(f"Found {len(topic_files)} topic metadata files.")

    # Load all existing metadata.
    topic_data = {}

    for path in topic_files:
        try:
            topic_data[path] = load_topic_json(path)
        except Exception as e:
            print(f"ERROR reading {path}: {e}")
            return

    # Build lookup of all existing problems.
    existing = {}

    for path, data in topic_data.items():
        for problem in data.get("problems", []):
            key = problem.get("problemName")

            if key:
                existing[(path, key)] = problem

    # Find all solution folders.
    solution_files = sorted(
        REPO.glob("*/*.cpp")
    )

    print(f"Found {len(solution_files)} C++ solution files.")

    print()
    print(
        "IMPORTANT: This script only updates Topics/*/problems.json."
    )
    print("It does NOT modify README.md.")
    print()

    # ------------------------------------------------------------
    # IMPORTANT
    #
    # We need problem metadata (difficulty + topics) from LeetCode.
    # This script expects a cache generated by run.py.
    # ------------------------------------------------------------

    cache_path = REPO / ".leethub_problem_cache.json"

    if not cache_path.exists():
        print(
            "ERROR: .leethub_problem_cache.json was not found."
        )
        print()
        print(
            "We need to make run.py save the LeetCode problemset "
            "response first."
        )
        return

    with open(cache_path, "r", encoding="utf-8") as f:
        problems = json.load(f)

    print(f"Loaded {len(problems)} problems from LeetCode cache.")
    print()

    added = 0
    skipped = 0

    for question in problems:

        frontend_id = str(question["questionFrontendId"])
        title = question["title"]
        slug = question["titleSlug"]
        difficulty = question["difficulty"].capitalize()

        try:
            number = int(frontend_id)
            problem_name = f"{number:04d}-{slug}"
        except ValueError:
            problem_name = f"{frontend_id}-{slug}"

        folder = REPO / problem_name
        cpp_file = folder / f"{problem_name}.cpp"

        if not cpp_file.exists():
            print(f"SKIP: {problem_name} - C++ file not found")
            skipped += 1
            continue

        sha = git_sha(cpp_file)

        topics = question.get("topicTags", [])

        if not topics:
            print(f"WARNING: {problem_name} has no topic tags")
            continue

        solution = {
            "language": "C++",
            "extension": ".cpp",
            "filename": f"{problem_name}.cpp",
            "path": f"{problem_name}/{problem_name}.cpp",
            "sha": sha,
            "lastSyncedAt": now_iso(),
        }

        problem_entry = {
            "frontendId": frontend_id,
            "title": title,
            "slug": slug,
            "problemName": problem_name,
            "difficulty": difficulty,
            "leetcodeUrl": f"https://leetcode.com/problems/{slug}/",
            "folderPath": f"{problem_name}/",
            "readmePath": f"{problem_name}/README.md",
            "solutions": [solution],
        }

        for topic in topics:

            topic_slug = topic["slug"]
            topic_file = TOPICS_DIR / topic_slug / "problems.json"

            if not topic_file.exists():
                print(
                    f"WARNING: Topic file doesn't exist: "
                    f"{topic_file}"
                )
                continue

            data = topic_data[topic_file]

            problems_list = data.setdefault("problems", [])

            found = None

            for existing_problem in problems_list:
                if existing_problem.get("problemName") == problem_name:
                    found = existing_problem
                    break

            if found:
                # Don't overwrite an existing Neo record.
                skipped += 1
                continue

            problems_list.append(problem_entry.copy())

            added += 1

            print(
                f"ADD: {problem_name} -> {topic_slug}"
            )

    # ------------------------------------------------------------
    # Save modified topic metadata
    # ------------------------------------------------------------

    changed_files = set()

    for path, data in topic_data.items():

        # Only save files that actually contain new entries.
        original = load_topic_json(path)

        if original != data:
            data["updatedAt"] = now_iso()
            save_topic_json(path, data)
            changed_files.add(path)

    print()
    print("=" * 70)
    print("Migration complete")
    print("=" * 70)
    print(f"Metadata entries added : {added}")
    print(f"Existing entries skipped: {skipped}")
    print(f"Topic files modified   : {len(changed_files)}")

    for path in sorted(changed_files):
        print(f"  {path}")


if __name__ == "__main__":
    main()
